@host = http://localhost:8080

### Home
GET {{host}}/home



### Login
POST {{host}}/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}



### Refresh
GET {{host}}/refresh